//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_info
    {
        public short id { get; set; }
        public string User_Account { get; set; }
        public string User_No { get; set; }
        public string User_Name_PY { get; set; }
        public string User_Name_CN { get; set; }
        public string User_Name_EN { get; set; }
        public string User_Dept { get; set; }
        public string User_Role { get; set; }
        public string User_Sub_Dept { get; set; }
        public string User_Team { get; set; }
        public string User_Sub_Team { get; set; }
    }
}
