//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TO_DB_CONN : DbContext
    {
        public TO_DB_CONN()
            : base("name=TO_DB_CONN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AA_Table_List> AA_Table_List { get; set; }
        public DbSet<Account_info> Account_info { get; set; }
        public DbSet<Lib_Fix_Options> Lib_Fix_Options { get; set; }
        public DbSet<Lib_Project_States> Lib_Project_States { get; set; }
        public DbSet<Lib_User_Role> Lib_User_Role { get; set; }
        public DbSet<Option_Base> Option_Base { get; set; }
        public DbSet<Project_Attached_Files> Project_Attached_Files { get; set; }
        public DbSet<Project_Base_Info> Project_Base_Info { get; set; }
        public DbSet<Project_Option_Info> Project_Option_Info { get; set; }
        public DbSet<Project_Product_Spec> Project_Product_Spec { get; set; }
        public DbSet<Project_States> Project_States { get; set; }
        public DbSet<Project_Units_Info> Project_Units_Info { get; set; }
    }
}
