//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib_Fix_Options
    {
        public int ID { get; set; }
        public string Option_Code { get; set; }
        public string Fix_Option_Description { get; set; }
        public string Products { get; set; }
        public Nullable<decimal> Fix_Tender_ME_Hours { get; set; }
        public Nullable<decimal> Fix_Tender_EE_Hours { get; set; }
        public Nullable<decimal> Fix_Order_ME_Hours { get; set; }
        public Nullable<decimal> Fix_Order_EE_Hours { get; set; }
        public string Fix_Option_Type { get; set; }
        public string Fix_Option_Remark { get; set; }
        public bool Valuable_Or_Not { get; set; }
        public string Related_FG { get; set; }
        public string Fix_Option_Input_Mask { get; set; }
    }
}
