//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option_Base
    {
        public int id { get; set; }
        public string Option_Code { get; set; }
    }
}
