//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Product_Spec
    {
        public int ID { get; set; }
        public string Project_No { get; set; }
        public Nullable<short> Tender_Version { get; set; }
        public string Product_Name { get; set; }
        public string Units_Specification { get; set; }
        public Nullable<short> Units_Quantity { get; set; }
        public string Units_Equipment_No { get; set; }
        public string OF_Name { get; set; }
        public string OF_File_Name { get; set; }
        public string Layout_Name { get; set; }
        public string Layout_File_Name { get; set; }
    }
}
