//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Base_Info
    {
        public int Id { get; set; }
        public string Project_No { get; set; }
        public short Tender_Version { get; set; }
        public string Project_Name { get; set; }
        public string KONE_FL { get; set; }
        public string KONE_FL_Person { get; set; }
        public string CS_Person { get; set; }
        public string OE_response_ME { get; set; }
        public string OE_response_EE { get; set; }
        public string Special_Requirement { get; set; }
        public Nullable<System.DateTime> Receive_Date { get; set; }
        public Nullable<byte> Receive_Week { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<System.DateTime> Reply_Date { get; set; }
        public Nullable<System.DateTime> NRP_Date { get; set; }
        public string Current_Owner { get; set; }
        public string Change_History { get; set; }
        public Nullable<bool> Order_Mark { get; set; }
        public Nullable<short> Order_Version { get; set; }
        public Nullable<short> Project_State { get; set; }
        public Nullable<System.DateTime> Modified_Data { get; set; }
    }
}
