//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_States
    {
        public int ID { get; set; }
        public short States_Number { get; set; }
        public string States_Description { get; set; }
        public string States_Milestone { get; set; }
    }
}
