//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Attached_Files
    {
        public int Id { get; set; }
        public short Tender_Version { get; set; }
        public string Upload_Person { get; set; }
        public System.DateTime Upload_Time { get; set; }
        public string Upload_File_type { get; set; }
        public string Project_No { get; set; }
        public string File_Title { get; set; }
        public string File_Name { get; set; }
        public string MD5_Code { get; set; }
        public string File_Category { get; set; }
    }
}
