//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Units_Info
    {
        public int Id { get; set; }
        public string Project_No { get; set; }
        public short Order_Version { get; set; }
        public string Units_SAP_No { get; set; }
        public string Units_Equipment_No { get; set; }
        public string OF_Name { get; set; }
        public string OF_File_Address { get; set; }
        public string Layout_Name { get; set; }
        public string Layout_Address { get; set; }
    }
}
